"""empty message

Revision ID: 44860d859003
Revises: 7c7c174d2f62
Create Date: 2018-06-14 21:17:04.714642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44860d859003'
down_revision = '7c7c174d2f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('document_type', sa.String(length=60), nullable=True))
    op.add_column('projects', sa.Column('employee', sa.String(length=60), nullable=True))
    op.drop_index('name', table_name='projects')
    op.create_unique_constraint(None, 'projects', ['employee'])
    op.create_unique_constraint(None, 'projects', ['document_type'])
    op.drop_column('projects', 'IER_date')
    op.drop_column('projects', 'SOW_date')
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('projects', sa.Column('SOW_date', sa.DATE(), nullable=True))
    op.add_column('projects', sa.Column('IER_date', sa.DATE(), nullable=True))
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'projects', type_='unique')
    op.create_index('name', 'projects', ['name'], unique=True)
    op.drop_column('projects', 'employee')
    op.drop_column('projects', 'document_type')
    op.drop_column('projects', 'date')
    # ### end Alembic commands ###
