"""empty message

Revision ID: 4f1d2efd8662
Revises: 44860d859003
Create Date: 2018-06-14 22:05:08.160969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1d2efd8662'
down_revision = '44860d859003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('document_type', table_name='projects')
    op.drop_index('employee', table_name='projects')
    op.create_unique_constraint(None, 'projects', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.create_index('employee', 'projects', ['employee'], unique=True)
    op.create_index('document_type', 'projects', ['document_type'], unique=True)
    # ### end Alembic commands ###
