"""empty message

Revision ID: 7c7c174d2f62
Revises: c38f20419f09
Create Date: 2018-06-13 13:24:53.814628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c7c174d2f62'
down_revision = 'c38f20419f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('IER_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('SOW_date', sa.Date(), nullable=True))
    op.drop_column('projects', 'statementofwork')
    op.drop_column('projects', 'individualreport')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('individualreport', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('statementofwork', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('projects', 'SOW_date')
    op.drop_column('projects', 'IER_date')
    # ### end Alembic commands ###
