"""empty message

Revision ID: 7f93a3648d7c
Revises: 4f1d2efd8662
Create Date: 2018-06-15 20:14:17.830789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f93a3648d7c'
down_revision = '4f1d2efd8662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('doc_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'doc_name')
    # ### end Alembic commands ###
